### ISSUE TITLE
Multiple Errors: Call to undefined function ctype_space()

### ISSUE THREAD

**Issue by jerry-knight** [linuxserver/docker-grocy#28]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
No error boxes.

## Current Behavior
Error boxes on every page. Technical Details:
````
"{\"error_message\":\"Call to undefined function ctype_space()\",\"error_details\":{\"stack_trace\":\"#0 \\/app\\/grocy\\/vendor\\/ezyang\\/htmlpurifier\\/library\\/HTMLPurifier\\/Lexer\\/DirectLex.php(158): HTMLPurifier_Token_Text->__construct('{\\\"time\\\":1608648...')\\n#1 \\/app\\/grocy\\/vendor\\/ezyang\\/htmlpurifier\\/library\\/HTMLPurifier.php(213): HTMLPurifier_Lexer_DirectLex->tokenizeHTML('{\\\"time\\\":1608648...', Object(HTMLPurifier_Config), Object(HTMLPurifier_Context))\\n#2 \\/app\\/grocy\\/controllers\\/BaseController.php(205): HTMLPurifier->purify('{\\\"time\\\":1608648...')\\n#3 \\/app\\/grocy\\/controllers\\/UsersApiController.php(211): Grocy\\\\Controllers\\\\BaseController->GetParsedAndFilteredRequestBody(Object(Slim\\\\Http\\\\ServerRequest))\\n#4 \\/app\\/grocy\\/vendor\\/slim\\/slim\\/Slim\\/Handlers\\/Strategies\\/RequestResponse.php(43): Grocy\\\\Controllers\\\\UsersApiController->SetUserSetting(Object(Slim\\\\Http\\\\ServerRequest), Object(Slim\\\\Http\\\\Response), Array)\\n#5 \\/app\\/grocy\\/vendor\\/slim\\/slim\\/Slim\\/Routing\\/Route.php(384): Slim\\\\Handlers\\\\Strategies\\\\RequestResponse->__invoke(Array, Object(Slim\\\\Http\\\\ServerRequest), Object(Slim\\\\Http\\\\Response), Array)\\n#6 \\/app\\/grocy\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(81): Slim\\\\Routing\\\\Route->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#7 \\/app\\/grocy\\/middleware\\/JsonMiddleware.php(13): Slim\\\\MiddlewareDispatcher->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#8 \\/app\\/grocy\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(209): Grocy\\\\Middleware\\\\JsonMiddleware->__invoke(Object(Slim\\\\Http\\\\ServerRequest), Object(Slim\\\\MiddlewareDispatcher))\\n#9 \\/app\\/grocy\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#10 \\/app\\/grocy\\/vendor\\/slim\\/slim\\/Slim\\/Routing\\/Route.php(341): Slim\\\\MiddlewareDispatcher->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#11 \\/app\\/grocy\\/vendor\\/slim\\/slim\\/Slim\\/Routing\\/RouteRunner.php(84): Slim\\\\Routing\\\\Route->run(Object(Slim\\\\Http\\\\ServerRequest))\\n#12 \\/app\\/grocy\\/middleware\\/LocaleMiddleware.php(16): Slim\\\\Routing\\\\RouteRunner->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#13 \\/app\\/grocy\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(313): Grocy\\\\Middleware\\\\LocaleMiddleware->__invoke(Object(Slim\\\\Http\\\\ServerRequest), Object(Slim\\\\Routing\\\\RouteRunner))\\n#14 \\/app\\/grocy\\/middleware\\/AuthMiddleware.php(76): class@anonymous->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#15 \\/app\\/grocy\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(313): Grocy\\\\Middleware\\\\AuthMiddleware->__invoke(Object(Slim\\\\Http\\\\ServerRequest), Object(class@anonymous))\\n#16 \\/app\\/grocy\\/vendor\\/slim\\/slim\\/Slim\\/Middleware\\/RoutingMiddleware.php(59): class@anonymous->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#17 \\/app\\/grocy\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(147): Slim\\\\Middleware\\\\RoutingMiddleware->process(Object(Slim\\\\Http\\\\ServerRequest), Object(class@anonymous))\\n#18 \\/app\\/grocy\\/vendor\\/slim\\/slim\\/Slim\\/Middleware\\/ErrorMiddleware.php(107): class@anonymous->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#19 \\/app\\/grocy\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(147): Slim\\\\Middleware\\\\ErrorMiddleware->process(Object(Slim\\\\Http\\\\ServerRequest), Object(class@anonymous))\\n#20 \\/app\\/grocy\\/middleware\\/CorsMiddleware.php(30): class@anonymous->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#21 \\/app\\/grocy\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(313): Grocy\\\\Middleware\\\\CorsMiddleware->__invoke(Object(Slim\\\\Http\\\\ServerRequest), Object(class@anonymous))\\n#22 \\/app\\/grocy\\/vendor\\/slim\\/slim\\/Slim\\/MiddlewareDispatcher.php(81): class@anonymous->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#23 \\/app\\/grocy\\/vendor\\/slim\\/slim\\/Slim\\/App.php(215): Slim\\\\MiddlewareDispatcher->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#24 \\/app\\/grocy\\/vendor\\/slim\\/slim\\/Slim\\/App.php(199): Slim\\\\App->handle(Object(Slim\\\\Http\\\\ServerRequest))\\n#25 \\/app\\/grocy\\/app.php(77): Slim\\\\App->run()\\n#26 \\/app\\/grocy\\/public\\/index.php(45): require_once('\\/app\\/grocy\\/app....')\\n#27 {main}\",\"file\":\"\\/app\\/grocy\\/vendor\\/ezyang\\/htmlpurifier\\/library\\/HTMLPurifier\\/Token\\/Text.php\",\"line\":43}}"
````

## Steps to Reproduce

1. pulled the latest linuxserver/grocy image, v3.0.0
2. started the docker container
3. loaded the default stock summary page
4. observed multiple red error boxes, all with similar technical detail strings

## Environment
**OS:** Ubuntu 20.04
**CPU architecture:** x86_64
**How docker service was installed:** docker repo, docker version 20.10.1, build 831ebea

## Command used to create docker container (run/create/compose/screenshot)
````
sudo docker run -d --name=grocy -e PUID=1000 -e PGID=1000 -e TZ=US/Eastern -p 9283:80 -v ./config:/config --restart always linuxserver/grocy
````

## Docker logs

````
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
[cont-init.d] 50-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
````

**Comment by jerry-knight** [comment]
Sorry, I didn't see the other closed issue https://github.com/linuxserver/docker-grocy/issues/26, so this is a duplicate issue.. closing.
